# Generated by Django 3.1.2 on 2020-10-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='profile_pics/', width_field='width_field'),
        ),
    ]
