# Generated by Django 3.1.2 on 2020-10-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
