# Generated by Django 3.0.7 on 2020-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
