# Generated by Django 3.1.2 on 2020-11-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0003_registration_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_bank',
            name='level_id',
        ),
    ]
