# Generated by Django 3.1.2 on 2020-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0004_remove_question_bank_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='answer',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option2', 'option4')], max_length=100),
        ),
    ]
