# Generated by Django 3.1.2 on 2020-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0006_auto_20201204_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='answer',
            field=models.CharField(choices=[(models.CharField(max_length=100), models.CharField(max_length=100)), (models.CharField(max_length=100), models.CharField(max_length=100)), (models.CharField(max_length=100), models.CharField(max_length=100)), (models.CharField(max_length=100), models.CharField(max_length=100))], max_length=100),
        ),
    ]
