# Generated by Django 3.1.2 on 2020-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0007_auto_20201204_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
