# Generated by Django 3.1.2 on 2020-12-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0008_auto_20201204_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='registration_id',
            new_name='reg_id',
        ),
    ]
