# Generated by Django 3.1.2 on 2020-12-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0009_auto_20201204_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='exam_name',
            new_name='exam_id',
        ),
    ]
