# Generated by Django 3.1.2 on 2020-12-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0011_auto_20201205_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='no_ques_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='no_ques_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='no_ques_unattempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='no_ques_wrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
