# Generated by Django 3.1.2 on 2020-12-08 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0020_result_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='result',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
