# Generated by Django 3.1.2 on 2020-12-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0021_auto_20201208_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
