# Generated by Django 3.1.2 on 2020-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0022_delete_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
