# Generated by Django 3.1.2 on 2020-12-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0023_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_detail',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam_detail',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
