# Generated by Django 3.1.2 on 2020-12-17 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0026_auto_20201217_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_detail',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
