# Generated by Django 3.1.2 on 2020-12-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0032_auto_20201217_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_detail',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exam_detail',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
